"use strict";
const modules=[['inicio','⌂','Inicio'],['equipos','♙','Equipos'],['zonas','◈','Asignación de zonas'],['fixture','▦','Fixture y canchas'],['resultados','✓','Resultados'],['posiciones','▤','Posiciones y cruces'],['notificaciones','♧','Notificaciones'],['bufet','☕','Bufet'],['alojamiento','⌂','Alojamiento'],['configuracion','⚙','Configuración']];
const categorias=['+50','+60','+68'];
const nombres={'+50':['Cóndores','Albatros','Lobos del Sur','Pioneros','Horizonte','Cumbres'],'+60':['Alerces','Cardenales','Estepa','Puelches','Andes','Vientos'],'+68':['Raíces','Aurora','Costanera','Patagonia','Río Azul','Sol Naciente']};
let teams=Object.fromEntries(categorias.map(c=>[c,[...nombres[c]]]));let cat='+50',page='inicio',zones={},results={};
const $=s=>document.querySelector(s),escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function selector(){return `<div class="toolbar"><label for="categoria">Categoría: </label><select id="categoria">${categorias.map(c=>`<option ${c===cat?'selected':''}>${c}</option>`).join('')}</select></div>`}
function panel(title,content){return `<section class="panel"><h3>${title}</h3>${content}</section>`}
function card(title,value,desc){return `<div class="card"><span class="muted">${title}</span><strong>${value}</strong><span class="muted">${desc}</span></div>`}
function partidos(c){let z=zones[c]||[teams[c].slice(0,3),teams[c].slice(3,6)];return z.flatMap((g,k)=>[[0,1],[0,2],[1,2]].map(([a,b],i)=>({id:`${k}-${i}`,a:g[a],b:g[b],zona:k?'B':'A',cancha:(k*2+i)%4+1,fecha:k?'Sábado':'Viernes',hora:`${14+i}:00`})))}
function setCat(){const sel=$('#categoria');if(sel)sel.onchange=()=>{cat=sel.value;render()}}
function render(){ $('#nav').innerHTML=modules.map(([id,ic,name])=>`<button data-go="${id}" class="${id===page?'active':''}">${ic} &nbsp;${name}</button>`).join('');$('#pageTitle').textContent=modules.find(m=>m[0]===page)[2];let v='';
if(page==='inicio')v=`<div class="cards">${card('Equipos ficticios','18','6 por categoría')}${card('Categorías','3','+50 · +60 · +68')}${card('Zonas','2','Por categoría')}${card('Guardado','No','Simulación temporal')}</div>${panel('Conocé el asistente','<p class="muted">Recorré los diez módulos desde el menú. Podés cambiar nombres de equipos y simular sorteos de zonas. Todo se reinicia al recargar la página.</p>')}`;
if(page==='equipos')v=selector()+panel('Equipos ficticios · '+cat,`<p class="muted">Editá los nombres para experimentar. Máximo 6 equipos precargados por categoría; no se agregan ni se guardan equipos.</p><div class="tablewrap"><table><thead><tr><th>#</th><th>Nombre editable</th><th>Estado</th></tr></thead><tbody>${teams[cat].map((t,i)=>`<tr><td>${i+1}</td><td><input data-team="${i}" maxlength="42" value="${escapeHTML(t)}" aria-label="Equipo ${i+1}"></td><td><span class="pill">Ficticio</span></td></tr>`).join('')}</tbody></table></div><div class="toolbar" style="margin-top:16px"><button class="action" id="apply">Aplicar a esta simulación</button></div><p id="teammsg" class="muted" aria-live="polite"></p>`);
if(page==='zonas')v=selector()+panel('Sorteo de zonas · '+cat,`<p class="muted">Simulación con seis equipos ficticios, repartidos en dos zonas de tres. No produce actas ni documentos exportables.</p><div class="toolbar"><button class="action" id="draw">Simular sorteo</button><button class="action secondary" id="resetZones">Volver a distribución inicial</button></div><div id="zones"></div>`);
if(page==='fixture')v=selector()+panel('Fixture de ejemplo · '+cat,`<p class="muted">Programación ilustrativa de seis partidos por categoría. No se genera un fixture oficial.</p>${tablaPartidos(cat,false)}`);
if(page==='resultados')v=selector()+panel('Resultados de ejemplo · '+cat,`<p class="muted">Marcadores ilustrativos. Podés probar cambios locales, pero no se registran resultados.</p>${tablaPartidos(cat,true)}`);
if(page==='posiciones')v=selector()+panel('Posiciones y cruces · '+cat,`<p class="muted">Ejemplo visual de clasificación con equipos ficticios. Los cruces y podios no son resultados oficiales.</p><div class="zones">${(zones[cat]||[teams[cat].slice(0,3),teams[cat].slice(3)]).map((z,i)=>`<div class="zone"><h4>Zona ${i?'B':'A'}</h4>${z.map((t,j)=>`<div>${j+1}. ${escapeHTML(t)} <span class="tag">Ejemplo</span></div>`).join('')}</div>`).join('')}</div><p class="muted">Semifinales, tercer puesto y final: presentación ilustrativa, sin programación ni guardado.</p>`);
if(page==='notificaciones')v=panel('Tablero de avisos · Torneo Demostración',`<p class="muted">Comunicaciones ilustrativas de la organización. Los avisos son ficticios y no se envían a participantes.</p><div class="demo-alerts"><article class="demo-alert"><div class="demo-alert-top"><span class="demo-label">INSCRIPCIONES</span><span class="demo-date">15 NOV · 2026</span></div><h4>¡Falta muy poco para nuestro Torneo!</h4><p>¡Falta muy poco para nuestro Torneo! Recordá que podés inscribirte en nuestra página. ¡Te esperamos para compartir tres jornadas de Newcom!</p><span class="demo-alert-foot">Organización · Torneo Demostración</span></article><article class="demo-alert"><div class="demo-alert-top"><span class="demo-label amber">CAMBIO DE HORARIO</span><span class="demo-date">20 NOV · 2026</span></div><h4>Nuevo horario de inicio del torneo</h4><p>Informamos que el inicio de los partidos del viernes se reprogramó para las <strong>14:30 h</strong>, en lugar de las 14:00 h previstas inicialmente. Solicitamos a los equipos presentarse con anticipación para su acreditación.</p><span class="demo-alert-foot">Organización · Torneo Demostración</span></article></div>`);
if(page==='bufet')v=panel('Bufet del torneo · Menú de muestra',`<p class="muted">Carta y precios ficticios en pesos argentinos para presentar el módulo. No se reciben pedidos ni pagos.</p><div class="demo-cards"><article class="demo-product"><span class="demo-emoji">☕</span><div><span class="demo-label">BEBIDAS CALIENTES</span><h4>Café con leche</h4><p>Vaso mediano, disponible durante toda la jornada.</p><strong>$ 2.500</strong></div></article><article class="demo-product"><span class="demo-emoji">🥪</span><div><span class="demo-label">COMIDAS</span><h4>Sándwich de jamón y queso</h4><p>Pan fresco, opción para almuerzo rápido.</p><strong>$ 5.500</strong></div></article><article class="demo-product"><span class="demo-emoji">🥟</span><div><span class="demo-label">COMIDAS</span><h4>Empanadas (unidad)</h4><p>Sabores de carne, pollo o verdura.</p><strong>$ 2.200</strong></div></article><article class="demo-product"><span class="demo-emoji">💧</span><div><span class="demo-label">BEBIDAS FRÍAS</span><h4>Agua mineral 500 ml</h4><p>Con o sin gas, ideal para los intervalos.</p><strong>$ 1.800</strong></div></article><article class="demo-product"><span class="demo-emoji">🍌</span><div><span class="demo-label">COLACIONES</span><h4>Fruta de estación</h4><p>Banana o manzana, según disponibilidad.</p><strong>$ 1.500</strong></div></article><article class="demo-product"><span class="demo-emoji">🥤</span><div><span class="demo-label">BEBIDAS FRÍAS</span><h4>Gaseosa 500 ml</h4><p>Variedades clásicas y sin azúcar.</p><strong>$ 2.800</strong></div></article></div><div class="demo-info"><strong>Horarios de atención (ficticios)</strong><p>Viernes 14:00 a 20:00 · Sábado y domingo 09:00 a 19:00</p><p class="muted">Los productos, horarios y valores se muestran únicamente como ejemplo de funcionamiento.</p></div>`);
if(page==='alojamiento')v=panel('Alojamiento · Opciones de muestra',`<p class="muted">Establecimientos, contactos, disponibilidad y tarifas completamente ficticios. Este módulo ilustra cómo se ofrecería información a las delegaciones visitantes; no permite reservar.</p><div class="demo-stays"><article class="demo-stay"><div class="demo-stay-head"><span class="demo-stay-icon">⌂</span><span class="demo-label">HOTEL · EJEMPLO</span></div><h4>Hotel Costanera (ficticio)</h4><p>Habitaciones dobles y triples, desayuno incluido.</p><dl><div><dt>Zona</dt><dd>Centro · Viedma</dd></div><div><dt>Capacidad</dt><dd>2 a 3 personas</dd></div><div><dt>Tarifa orientativa</dt><dd>$ 65.000 / noche</dd></div></dl><span class="demo-stay-note">Datos simulados · Sin reservas</span></article><article class="demo-stay"><div class="demo-stay-head"><span class="demo-stay-icon">▦</span><span class="demo-label">APART · EJEMPLO</span></div><h4>Apart Río Sur (ficticio)</h4><p>Departamentos equipados con cocina, ideales para grupos.</p><dl><div><dt>Zona</dt><dd>Barrio residencial · Viedma</dd></div><div><dt>Capacidad</dt><dd>4 personas</dd></div><div><dt>Tarifa orientativa</dt><dd>$ 95.000 / noche</dd></div></dl><span class="demo-stay-note">Datos simulados · Sin reservas</span></article><article class="demo-stay"><div class="demo-stay-head"><span class="demo-stay-icon">♧</span><span class="demo-label">HOSTERÍA · EJEMPLO</span></div><h4>Hostería del Encuentro (ficticia)</h4><p>Habitaciones compartidas, desayuno y espacio de reunión.</p><dl><div><dt>Zona</dt><dd>Acceso norte · Viedma</dd></div><div><dt>Capacidad</dt><dd>2 a 5 personas</dd></div><div><dt>Tarifa orientativa</dt><dd>$ 42.000 / persona</dd></div></dl><span class="demo-stay-note">Datos simulados · Sin reservas</span></article></div><div class="demo-info"><strong>Información para delegaciones</strong><p>En una edición real, este espacio podría incluir distancias a las canchas, servicios disponibles, mapas y datos de contacto verificados.</p><p class="muted">No hay alojamientos reales ofrecidos en esta demostración.</p></div>`);
if(page==='configuracion')v=panel('Configuración de demostración',`<p class="muted"><strong>Torneo:</strong> Torneo Demostración<br><strong>Categorías:</strong> +50, +60 y +68<br><strong>Equipos:</strong> 6 por categoría<br><strong>Zonas:</strong> 2 por categoría<br><strong>Modo:</strong> interactivo temporal, sin guardado ni exportación</p><button class="action secondary" id="reset">Restablecer demostración</button>`);
$('#view').innerHTML=v;document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{page=b.dataset.go;render()});setCat();
if(page==='equipos')$('#apply').onclick=()=>{let vals=[...document.querySelectorAll('[data-team]')].map(e=>e.value.trim());if(vals.some(x=>!x)||new Set(vals.map(x=>x.toLowerCase())).size!==6){$('#teammsg').textContent='Los seis equipos deben tener nombres diferentes y no vacíos.';$('#teammsg').className='error';return}teams[cat]=vals;delete zones[cat];$('#teammsg').textContent='Cambios aplicados solo a esta simulación. No se guardaron.';$('#teammsg').className='muted'};
if(page==='zonas'){const show=()=>$('#zones').innerHTML=`<div class="zones">${(zones[cat]||[teams[cat].slice(0,3),teams[cat].slice(3)]).map((g,i)=>`<div class="zone"><h4>Zona ${i?'B':'A'}</h4>${g.map(t=>`<div>${escapeHTML(t)}</div>`).join('')}</div>`).join('')}</div>`;show();$('#draw').onclick=()=>{let arr=[...teams[cat]];for(let i=arr.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[arr[i],arr[j]]=[arr[j],arr[i]]}zones[cat]=[arr.slice(0,3),arr.slice(3)];show()};$('#resetZones').onclick=()=>{delete zones[cat];show()}};
if(page==='resultados')document.querySelectorAll('[data-score]').forEach(e=>e.onchange=()=>{results[cat+'-'+e.dataset.score]=e.value});
if(page==='configuracion')$('#reset').onclick=()=>{teams=Object.fromEntries(categorias.map(c=>[c,[...nombres[c]]]));zones={};results={};cat='+50';page='inicio';render()};}
function tablaPartidos(c,edit){return `<div class="tablewrap"><table><thead><tr><th>Zona</th><th>Encuentro ficticio</th><th>Día</th><th>Hora</th><th>Cancha</th>${edit?'<th>Set 1 (simulación)</th>':''}</tr></thead><tbody>${partidos(c).map(p=>`<tr><td>${p.zona}</td><td>${escapeHTML(p.a)} vs ${escapeHTML(p.b)}</td><td>${p.fecha}</td><td>${p.hora}</td><td>${p.cancha}</td>${edit?`<td><input data-score="${p.id}" style="width:105px" placeholder="15-12" maxlength="7" value="${escapeHTML(results[c+'-'+p.id]||'')}"></td>`:''}</tr>`).join('')}</tbody></table></div>`}
render();